

spring:
  datasource-write:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://192.168.50.117:5000/postgres
    username: 'postgres'
    password: 'secret123'
    platform: postgresql
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: WriteHikariPool

  datasource-read:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://192.168.50.117:5001/postgres
    username: 'postgres'
    password: 'secret123'
    platform: postgresql
    hikari:
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5
      pool-name: ReadHikariPool
server:
  port: 9000

mybatis-plus:
  configuration:
    #  specification If the database field is order_id, then the entity field should be written as orderId
    map-underscore-to-camel-case: true
  #Mybatis mapper.xml file location
  mapper-locations: classpath*:**/sql/*.xml